apiVersion: apps/v1
kind: Deployment
metadata:
  name: g37-lanches-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: g37-lanches-api
  template:
    metadata:
      labels:
        app: g37-lanches-api
    spec:
      containers:
        - name: g37-lanches-api
          image: igorramos/g37-lanches-api:v1.0.3
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
              name: db-secret
          env:
            - name: ENVIRONMENT
              value: prod
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: POSTGRES_DBNAME
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: POSTGRES_PORT
            - name: POSTGRES_SSLMODE
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: POSTGRES_SSLMODE
                
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.25"
              memory: "256Mi"