apiVersion: apps/v1
kind: Deployment
metadata:
  name: g37-lanches-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: g37-lanches-api
  template:
    metadata:
      labels:
        app: g37-lanches-api
    spec:
      containers:
        - name: g37-lanches-api
          image: igorramos/g37-lanches-api:v1.0.3
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: dev
            - name: POSTGRES_HOST
              value: $(POSTGRES_HOST)
            - name: POSTGRES_DB
              value: $(POSTGRES_DBNAME)
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_SSLMODE
              value: disable
            - name: POSTGRES_USERNAME
              value: $(POSTGRES_USERNAME)
            - name: POSTGRES_PASSWORD
              value: $(POSTGRES_PASSWORD)
                
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.25"
              memory: "256Mi"